// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd4zeUGlsipMxrT6sym2yY13BBoOw88nM',
    appId: '1:976615675970:android:6e3c5fa252d0ea1b9a75db',
    messagingSenderId: '976615675970',
    projectId: 'ibct-eventos-e1751',
    storageBucket: 'ibct-eventos-e1751.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb-bQZiI7nwqa1qR_o4ZsWMFGg1rT9O6U',
    appId: '1:976615675970:web:a034509d2780a0119a75db',
    messagingSenderId: '976615675970',
    projectId: 'ibct-eventos-e1751',
    authDomain: 'ibct-eventos-e1751.firebaseapp.com',
    storageBucket: 'ibct-eventos-e1751.firebasestorage.app',
    measurementId: 'G-YKFEQ9PK0L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-War_QDb6O495KwbQECsIJq-oy7_S6Go',
    appId: '1:976615675970:ios:325507c15c4ad5be9a75db',
    messagingSenderId: '976615675970',
    projectId: 'ibct-eventos-e1751',
    storageBucket: 'ibct-eventos-e1751.firebasestorage.app',
    androidClientId: '976615675970-8ihv3vvq4if7uanepftgamkukpb4lnmf.apps.googleusercontent.com',
    iosClientId: '976615675970-hv3utpfpbnick943n5dofro6krtpgbcu.apps.googleusercontent.com',
    iosBundleId: 'br.com.ibct.eventos',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-War_QDb6O495KwbQECsIJq-oy7_S6Go',
    appId: '1:976615675970:ios:34eb6e6528bda1df9a75db',
    messagingSenderId: '976615675970',
    projectId: 'ibct-eventos-e1751',
    storageBucket: 'ibct-eventos-e1751.firebasestorage.app',
    androidClientId: '976615675970-8ihv3vvq4if7uanepftgamkukpb4lnmf.apps.googleusercontent.com',
    iosClientId: '976615675970-srn2qhup26olh6qperu042igjsqvjoo8.apps.googleusercontent.com',
    iosBundleId: 'br.com.ibct.eventos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb-bQZiI7nwqa1qR_o4ZsWMFGg1rT9O6U',
    appId: '1:976615675970:web:b2c82f9660934a2c9a75db',
    messagingSenderId: '976615675970',
    projectId: 'ibct-eventos-e1751',
    authDomain: 'ibct-eventos-e1751.firebaseapp.com',
    storageBucket: 'ibct-eventos-e1751.firebasestorage.app',
    measurementId: 'G-J2L3C016YJ',
  );

}
